name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.ARMBIAN_SELF_DISPATCH_TOKEN }}"  # GitHub token
          armbian_release:   "noble"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "oec-box-wxy4"                 # build target
